# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0005_auto_20180113_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='time_unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='time_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='membershipbenefits',
            name='name',
            field=models.CharField(blank=True, choices=[('CR', 'Conference Room'), ('DD', 'Dedicated Desks'), ('ES', 'Event Space'), ('FD', 'Flexible Desks'), ('PS', 'Private Studios'), ('VO', 'Virtual Office')], max_length=300, null=True),
        ),
    ]
