# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0008_cowork_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='price_per_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cowork',
            name='price_per_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
