# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0009_auto_20180113_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='no_of_workstattion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
