# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0011_membershipbenefits_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image/'),
        ),
    ]
