# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0015_pricing_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='locality',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cowork',
            name='parent_cowork',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
