# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0016_auto_20180122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='filter',
            field=models.CharField(blank=True, choices=[('W', 'Work'), ('FS', 'Facilities & Support'), ('EA', 'Events & Activities'), ('FK', 'Food & Kitchen'), ('PA', 'Payable Amenties'), ('OA', 'Other Amenities')], max_length=5, null=True),
        ),
    ]
