# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0018_auto_20180126_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='reasons_to_choose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
