# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0019_cowork_reasons_to_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='filter_css_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
