# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0020_amenity_filter_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipbenefits',
            name='name',
            field=models.CharField(blank=True, choices=[('CR', 'Conference Room'), ('DD', 'Dedicated Desks'), ('ES', 'Event Space'), ('FD', 'Flexible Desks'), ('PS', 'Private Office'), ('VO', 'Virtual Office')], max_length=300, null=True),
        ),
    ]
