# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworks', '0021_auto_20180201_1716'),
        ('core', '0003_auto_20180120_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='cowork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_cowork', to='coworks.Cowork'),
        ),
    ]
