# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactus_cowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
